name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name:  check images
      run: docker images

    - name: push to docker registry
      run: docker login -u sanket0770 -p dckr_pat_JSChm8l6s9qImfRf7yDGWsbhfoc
    
