name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
          
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name:  check images
      run: docker images

    - name: push to docker registry
      run: |
        docker login -u ${{vars.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
        docker tag my-image-name:latest sanket0770/django-image:latest
        docker push sanket0770/django-image:latest
      
    
