name: label created

on:
  issues:
    types: [opened]
  push:
    branches: [main]

jobs:

  send-msg:
  
    runs-on: ubuntu-latest

    steps:
    - name: Send email
  # You may pin to the exact commit or the version.
  # uses: dawidd6/action-send-mail@2cea9617b09d79a095af21254fbcb7ae95903dde
      uses: dawidd6/action-send-mail@v3.12.0
      with:

        # SMTP server address
        server_address: smtp.gmail.com
        # SMTP server port
        server_port: 465
        # Whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Authenticate as this user to SMTP server
        username: sanket13sp@gmail.com
        # Authenticate with this password to SMTP server
        password: sanket&1998
        # Subject of mail message
        subject: New issue opened
        to: 13sanketsp@gmail.com
        # Full name of mail sender (might be with an email address specified in <>)
        from: sanket13sp@gmail.com
        # Body of mail message (might be a filename prefixed with file:// to read from)
        body: new ticked opened
        # HTML body of mail message (might be a filename prefixed with file:// to read from)
        # html_body: # optional
        # Carbon copy recipients (separated with comma)
        # cc: # optional
        # Blind carbon copy recipients (separated with comma)
        # bcc: # optional
        # An email address that will appear on the Reply-To field
        # reply_to: # optional
        # The Message-ID this message is replying to
        # in_reply_to: # optional
        # Allow unsigned/invalid certificates
        # ignore_cert: # optional
        # Convert body from Markdown to HTML (set content_type input as text/html too)
        #convert_markdown: # optional
        # Files that will be added to mail message attachments (separated with comma)
        #attachments: # optional
        # Set Priority level for the mail message to 'high', 'normal' (default) or 'low'
       # priority: # optional
        # Log option for nodemailer
       # nodemailerlog: # optional
        # Debug option for nodemailer
        #nodemailerdebug: # optional
            
    



    
  
  
