name: label created

on:
  issues:
    types: [opened]
  push:
    branches: [main]

jobs:

  send-msg:
  
    runs-on: ubuntu-latest

    steps:
        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"          
    



    
  
  
